### ISSUE TITLE
Broken since el capitan (?) or SFML 2.3.1?

### ISSUE THREAD

**Issue by sharpner** [SFML/CSFML#91]
Today I found out that my code does not compile anymore. 
`fatal error: 'SFML/Graphics/RenderWindow.h' file not found
#include <SFML/Graphics/RenderWindow.h>`

I then tried the brew test formula, that also breaks:
```bash
$ brew test csfml
Testing csfml
==> /usr/bin/clang test.c -lcsfml-window -o test
Last 15 lines from /Users/username/Library/Logs/Homebrew/csfml/01.clang:
2015-10-16 08:39:44 +0200

/usr/bin/clang
test.c
-lcsfml-window
-o
test

ld: library not found for -lcsfml-window
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: csfml: failed
Failed executing: /usr/bin/clang test.c -lcsfml-window -o test
/usr/local/Library/Homebrew/formula.rb:1353:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1290:in `open'
/usr/local/Library/Homebrew/formula.rb:1290:in `system'
/usr/local/Library/Formula/csfml.rb:35:in `block in <class:Csfml>'
/usr/local/Library/Homebrew/formula.rb:1199:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1195:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

Any hints?

**Comment by eXpl0it3r** [comment]
Sounds like the SFML libs and headers aren't installed. Did you check that they actually exist?

**Comment by sharpner** [comment]
Yeah I did, I also reinstalled those files and tried compiling it with a simple c file. 
The only thing I noticed was that I had sfml 2.3.1 and csfml 2.3. 

But maybe I need to reaccept the stupid Xcode license, thx for the hint...

**Comment by sharpner** [comment]
Yeah nevermind, I had to accept that f*** license. Thanks for your time ;)
